version: '3.3'
services:
  address-book-db:
    image: postgres:16
    container_name: address-book-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ~/ws/address-book-db-volume:/var/lib/postgresql/data
    networks:
      - address-book-network
  address-book-backend:
    build:
      context: ../address-book-backend
      args:
        DOCKER_BUILDKIT: 1
    image: address-book-backend
    container_name: address-book-backend
    env_file:
      - ../address-book-backend/.env
    ports:
      - "7088:7088"
    volumes:
      - "${HOME}/.m2:/root/.m2"
    depends_on:
      - address-book-db
    networks:
      - address-book-network
  address-book-frontend:
    build: ../address-book-frontend
    image: address-book-frontend
    container_name: address-book-frontend
    ports:
      - "4200:80"
    depends_on:
      - address-book-backend
    networks:
      - address-book-network
networks:
  address-book-network:
