apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "address-book-db"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: address-book-backend
                  key: SPRING_DATASOURCE_PASSWORD
          ports:
            - containerPort: 5432